-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, c.CATEGORY, SUM(c.TOTAL) as TOTAL_SALES
FROM AUTHOR a JOIN (
    SELECT b.BOOK_ID, b.CATEGORY, b.AUTHOR_ID, SUM(s.SALES) * b.PRICE as TOTAL
    FROM BOOK b JOIN BOOK_SALES s
    ON b.BOOK_ID = s.BOOK_ID
    WHERE s.SALES_DATE LIKE '2022-01%'
    GROUP BY s.BOOK_ID
) c
ON a.AUTHOR_ID = c.AUTHOR_ID
GROUP BY a.AUTHOR_ID, c.CATEGORY
ORDER BY a.AUTHOR_ID ASC, c.CATEGORY DESC