-- 코드를 작성해주세요
SELECT d.id, IFNULL(p.COUNT, 0) as CHILD_COUNT
FROM ECOLI_DATA d LEFT OUTER JOIN (
    SELECT PARENT_ID, COUNT(*) as COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) p
ON d.id = p.PARENT_ID
ORDER BY d.id ASC