-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, p.PRICE * s.SUM_AMOUNT as SALES
FROM PRODUCT p JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) as SUM_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) s
ON p.PRODUCT_ID = s.PRODUCT_ID
ORDER BY SALES DESC, p.PRODUCT_CODE ASC