-- 코드를 입력하세요
SELECT b.FOOD_TYPE, b.REST_ID, b.REST_NAME, b.FAVORITES
FROM REST_INFO b JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) as FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ORDER BY FOOD_TYPE DESC
) a
ON (b.FOOD_TYPE, b.FAVORITES) = (a.FOOD_TYPE, a.FAVORITES)
ORDER BY b.FOOD_TYPE DESC