-- 코드를 작성해주세요
SELECT ID, 
    CASE
        WHEN PERCENT <= 0.25 THEN 'CRITICAL'
        WHEN PERCENT <= 0.5 THEN 'HIGH'
        WHEN PERCENT <= 0.75 THEN 'MEDIUM'
        WHEN PERCENT <= 1 THEN 'LOW'
    END as COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) as PERCENT
    FROM ECOLI_DATA
) as p
ORDER BY ID ASC
