-- 코드를 입력하세요
SELECT YEAR(s.SALES_DATE) as YEAR, MONTH(s.SALES_DATE) as MONTH, u.GENDER, COUNT(DISTINCT s.USER_ID) as USERS
FROM USER_INFO u JOIN ONLINE_SALE s
ON u.USER_ID = s.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, u.GENDER
ORDER BY YEAR, MONTH, u.GENDER