-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS
# WHERE SKILL_1 = 'PYTHON' or SKILL_2 = 'PYTHON' or SKILL_3 = 'PYTHON'
WHERE 'PYTHON' IN (SKILL_1, SKILL_2, SKILL_3)
ORDER BY ID ASC