-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)

SELECT h.HOUR as HOUR, COUNT(o.ANIMAL_ID) as COUNT
FROM ANIMAL_OUTS o RIGHT OUTER JOIN HOURS h
ON HOUR(o.DATETIME) = h.HOUR
GROUP BY h.HOUR
ORDER BY h.HOUR ASC