# -- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, b.TOTAL_SALES
FROM USED_GOODS_USER u JOIN (
    SELECT WRITER_ID, SUM(PRICE) as TOTAL_SALES
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID, STATUS
    HAVING TOTAL_SALES >= 700000 AND STATUS = 'DONE'
) b
ON u.USER_ID = b.WRITER_ID
ORDER BY b.TOTAL_SALES ASC
