-- 코드를 작성해주세요
SELECT s.YEAR, (MAX_V - d.SIZE_OF_COLONY) as YEAR_DEV, d.ID
FROM ECOLI_DATA d
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as MAX_V
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) s
ON YEAR(d.DIFFERENTIATION_DATE) = s.YEAR
ORDER BY s.YEAR ASC, YEAR_DEV ASC