-- 코드를 작성해주세요
SELECT g.SCORE, g.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES e JOIN (
    SELECT SUM(SCORE) as SCORE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
) g
ON e.EMP_NO = g.EMP_NO