-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', b.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) as FILE_PATH
FROM USED_GOODS_FILE f JOIN USED_GOODS_BOARD b
ON f.BOARD_ID = b.BOARD_ID
WHERE b.VIEWS = (
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD
)
ORDER BY f.FILE_ID DESC