-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(s.SALES) as TOTLA_SALES
FROM BOOK b JOIN (
    SELECT BOOK_ID, SUM(SALES) as SALES
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID
) s
ON b.BOOK_ID = s.BOOK_ID
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC