-- 코드를 작성해주세요
SELECT COUNT(*) as FISH_COUNT, MAX(LENGTH) as MAX_LENGTH, FISH_TYPE
FROM (
    SELECT ID, FISH_TYPE, TIME,
        CASE
            WHEN LENGTH <= 10 OR LENGTH IS NULL THEN 10
            ELSE LENGTH
        END as LENGTH
    FROM FISH_INFO
) as NEW
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE ASC