-- 코드를 작성해주세요
WITH SKILL_CONDITION AS (
    SELECT NAME, CODE FROM SKILLCODES WHERE NAME = 'Python'
    UNION ALL
    SELECT NAME, CODE FROM SKILLCODES WHERE NAME = 'C#'
    UNION ALL
    SELECT CATEGORY AS NAME, BIT_OR(CODE) FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
    GROUP BY CATEGORY
),
MATCHED AS (
    SELECT d.ID, d.EMAIL, GROUP_CONCAT(c.NAME) AS SKILL_NAMES
    FROM SKILL_CONDITION c JOIN DEVELOPERS d
    ON c.CODE & d.SKILL_CODE > 0
    GROUP BY d.ID, d.EMAIL
)

SELECT CASE
    WHEN SKILL_NAMES LIKE '%Front End%' AND SKILL_NAMES LIKE '%Python%' THEN 'A'
    WHEN SKILL_NAMES LIKE '%C#%' THEN 'B'
    WHEN SKILL_NAMES LIKE '%Front End%' THEN 'C'
END AS GRADE, ID, EMAIL
FROM MATCHED
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC
